#
# Makefile for all kinds of Fingerprint
#

#obj-y += focaltech/
#obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
#obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
#Begin added by zhihua.fangzhihua for ICNT7151L on 2017/11/17
obj-$(CONFIG_FPSENSOR_FINGERPRINT_MTK_U5APLUS_ICNT7151) += fpsensor_tee/
#end added by zhihua.fangzhihua for ICNT7151L on 2017/11/17
#obj-$(CONFIG_FPC_FINGERPRINT_TEE) += fpc_tee/
